//! The golden tests of `cardano-crypto` (`tests/goldens/cardano/crypto/`,
//! generated by its `GoldenTest.hs` from the C code the node links), run
//! against [`ouroboros_crypto_kit::byron`].
//!
//! * `wallet-BIP39-*`: from a seed, run a master key generation (`retry-old`
//!   is `Wallet.generate`, `pbkdf` is `Wallet.generateNew`), derive along a
//!   path with one of the two schemes, and sign `data_to_sign`; the files give
//!   the resulting `XPrv`, `XPub` and signature.
//! * `signature-ed25519`: `Wallet.verify` of a signature under an `XPub`.
//!
//! The BIP39 mnemonic in each wallet vector is not used: the seed it produces
//! is given alongside it.

use ouroboros_crypto_kit::byron::{self, DerivationScheme, XPub};
use ouroboros_crypto_kit::ed25519::Signature;

fn hex(s: &str) -> Vec<u8> {
    fn nibble(c: u8) -> u8 {
        match c {
            b'0'..=b'9' => c - b'0',
            b'a'..=b'f' => c - b'a' + 10,
            b'A'..=b'F' => c - b'A' + 10,
            _ => panic!("invalid hex digit {:?}", c as char),
        }
    }
    let b = s.as_bytes();
    assert!(b.len() % 2 == 0, "odd length hex string: {s}");
    b.chunks(2)
        .map(|p| (nibble(p[0]) << 4) | nibble(p[1]))
        .collect()
}

type Fields = std::collections::HashMap<String, String>;

/// Split a golden file into its `TestVector` records of `key = value` fields.
/// A value continues on the following lines until its brackets balance, which
/// is how the multi-element `path` lists are written.
fn parse(content: &str) -> Vec<(String, Fields)> {
    let mut out = Vec::new();
    let mut title = String::new();
    let mut lines = content.lines().peekable();
    while let Some(line) = lines.next() {
        if let Some(t) = line.strip_prefix("# ") {
            title = t.to_string();
        } else if line == "TestVector" {
            out.push((title.clone(), Fields::new()));
        } else if let Some((k, v)) = line.split_once(" = ") {
            let mut v = v.to_string();
            while v.matches('[').count() > v.matches(']').count() {
                v.push_str(lines.next().expect("unterminated list"));
            }
            let v = v.trim().trim_matches('"').to_string();
            out.last_mut()
                .expect("field before TestVector")
                .1
                .insert(k.to_string(), v);
        }
    }
    out
}

fn get<'a>(name: &str, f: &'a Fields, k: &str) -> &'a str {
    f.get(k)
        .unwrap_or_else(|| panic!("{name}: missing field {k}"))
}

fn path(s: &str) -> Vec<u32> {
    s.trim_matches(|c| c == '[' || c == ']')
        .split(',')
        .map(str::trim)
        .filter(|x| !x.is_empty())
        .map(|x| x.parse().expect("derivation index"))
        .collect()
}

fn read(name: &str) -> String {
    let file = format!("{}/tests/data/byron/{name}", env!("CARGO_MANIFEST_DIR"));
    std::fs::read_to_string(&file).unwrap_or_else(|e| panic!("{file}: {e}"))
}

#[test]
fn wallet_goldens() {
    let mut count = 0;
    for bits in [128, 160, 192, 224, 256] {
        let file = format!("wallet-BIP39-{bits}");
        for (title, f) in parse(&read(&file)) {
            let name = format!("{file} {title}");
            let passphrase = get(&name, &f, "passphrase").as_bytes();
            let seed = hex(get(&name, &f, "seed"));
            let scheme = match get(&name, &f, "derivation_scheme") {
                "derivation-scheme1" => DerivationScheme::V1,
                "derivation-scheme2" => DerivationScheme::V2,
                other => panic!("{name}: unknown scheme {other}"),
            };
            let master = match get(&name, &f, "master_key_generation") {
                "retry-old" => byron::generate(&seed, passphrase).expect("seed of 32+ bytes"),
                "pbkdf" => byron::generate_new(&seed, b"", passphrase),
                other => panic!("{name}: unknown generation {other}"),
            };
            let key = path(get(&name, &f, "path"))
                .into_iter()
                .fold(master, |k, i| k.derive(scheme, passphrase, i));

            assert_eq!(
                key.as_bytes()[..],
                hex(get(&name, &f, "xPriv"))[..],
                "{name}: xPriv"
            );
            let xpub = key.to_xpub();
            assert_eq!(
                xpub.as_bytes()[..],
                hex(get(&name, &f, "xPub"))[..],
                "{name}: xPub"
            );

            let message = get(&name, &f, "data_to_sign").as_bytes();
            let sig = key.sign(passphrase, message);
            assert_eq!(
                sig.as_bytes()[..],
                hex(get(&name, &f, "signature"))[..],
                "{name}: signature"
            );
            assert!(xpub.verify(message, &sig), "{name}: verify");
            count += 1;
        }
    }
    assert_eq!(count, 51);
}

#[test]
fn signature_goldens() {
    let vectors = parse(&read("signature-ed25519"));
    assert_eq!(vectors.len(), 9);
    for (name, f) in vectors {
        let xpub = XPub::from_slice(&hex(get(&name, &f, "xpub"))).expect("64-byte xpub");
        let sig =
            Signature::from_slice(&hex(get(&name, &f, "signature"))).expect("64-byte signature");
        let expected = get(&name, &f, "valid") == "true";
        assert_eq!(
            xpub.verify(&hex(get(&name, &f, "data")), &sig),
            expected,
            "{name}"
        );
    }
}
